### ISSUE TITLE
Commercial uses

### ISSUE THREAD

**Issue by seqlt** [Meghansaha/Intro_to_Data_Art#1]
Dear Meghan,

I am one of the R users and I find your Data Art very fascinating. As I am also an NFT creator, so I was wondering if I could use and adapt your code (https://www.thetidytrekker.com/post/thinking-outside-the-grid?fbclid=IwAR1KrrXCzARDcR_Co3OlD9TbxJ8PtIjY9SFFS3kKURKzBaZhyEMamrrvAZ4) to produce NFTs? 
Of course, the final products will also be sold on the NFT platform, so I think it is crucial to make sure with you first. 
Please let me know what you think?

Best regards,
Seqlt

**Comment by Meghansaha** [comment]
Hello SeqIt,

This code that I post publicly is intended for learning purposes and not really for commercial use. I think I'd be more interested in learning what specific code you will be adapting from as I have my own variations that I've set aside for sale in the future on physical mediums. I usually ask that if my code is recognizable/identifiable to me that I'm attributed. 

But if you're just using it as a foundation to create your own, I would see it as your own code at that point. If you'd like, you can e-mail me directly (I don't check GitHub too often some days - meghansa@buffalo.edu) to just let me know which code you're using! Depending on which one, I'd probably have no problem with you adapting it for this purpose. Just let me know either way. Thank you for taking the time to ask. I appreciate it!
